// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Developer",
            "email": "intanmarsjaf@outlook.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/master/api": {
            "get": {
                "description": "This is API to get list of public API by auth or category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List Public API",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Params 1",
                        "name": "auth",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Params 2",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.BadRequestResponse"
                        }
                    }
                }
            }
        },
        "/master/university": {
            "get": {
                "description": "This is API to get list university",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List University",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Params 1",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Params 2",
                        "name": "country",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.BadRequestResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.BadRequestResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "004"
                },
                "message": {
                    "type": "string",
                    "example": "[message]"
                },
                "result": {
                    "type": "string",
                    "example": "null"
                }
            }
        },
        "domain.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "000"
                },
                "message": {
                    "type": "string",
                    "example": "[message]"
                },
                "result": {
                    "type": "object"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3040",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "GOUNIV",
	Description:      "This page is API documentation for master data of university in the world",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
